### ISSUE TITLE
Make output parseable

### ISSUE THREAD

**Issue by goldmann** [goldmann/docker-scripts#12]
Sometimes it would be good to have the output parseable so other tools could benefit from it, even if not written in Python.

What format it should take? Or maybe it should just output the plain messages?

/cc @bparees

**Comment by bparees** [comment]
so the output i'm concerned w/ is the layer output, for which i'd say just print the layers and optionally the affiliated tag name.  Do away with the tree annotation and indentation.

**Comment by goldmann** [comment]
Oh, I think you just missed the `-m` switch in that case.

**Comment by bparees** [comment]
-m appears to be incompatible with -t

**Comment by goldmann** [comment]
Then that's a bug, I'll take care of it. I must admit that I reworked tagging, give me a sec, or two.

**Comment by goldmann** [comment]
Does something like this work for you? Multiple tags will be separated by comma.

```
$ python docker_scripts/cli.py layers jboss/wildfly -tm
511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158|
782cf93a8f16d3016dae352188cd5cfedb6a15c37d4dbd704399f02d1bb89dab|
7d3f07f8de5fb3a20c6cb1e4447773a5741e3641c1aa093366eaa0fc690c6417|
1ef0a50fe8b1394d3626a7624a58b58cff9560ddb503743099a56bbe95ab481a|
20a1abe1d9bfb9b1e46d5411abd5a38b6104a323b7c4fb5c0f1f161b8f7278c2|
cd5bb934bb6755e910d19ac3ae4cfd09221aa2f98c3fbb51a7486991364dc1ae|
379edb00ab0764276787ea777243990da697f2f93acb5d9166ff73ad01511a87|
4d37cbbfc67dd508e682a5431a99d8c1feba1bd8352ffd3ea794463d9cfa81cc|
2ea8562cac7c25a308b4565b66d4f7e11a1d2137a599ef2b32ed23c78f0a0378|docker.io/jboss/base:latest
7759146eab1a3aa5ba5ed12483d03e64a6bf1061a383d5713a5e21fc40554457|
b17a20d6f5f8e7ed0a1dba277acd3f854c531b0476b03d63a8f0df4caf78c763|
e02bdb6c4ed5436da02c958d302af5f06c1ebb1821791f60d45e190ebb55130f|
72d585299bb5c5c1c326422cfffadc93d8bb4020f35bf072b2d91d287967807a|
90832e1f0bb9e9f98ecd42f6df6b124c1e6768babaddc23d646cd75c7b2fddec|docker.io/jboss/base-jdk:7
b2b7d0c353b9b7500d23d2670c99abf35c4285a5f396df7ef70386848b45d162|
3759d5cffae63d6ddc9f2db9142403ad39bd54e305bb5060ae860aac9b9dec1d|
5c98b1e90cdcdb322601091f1f8654bc551015caa9ec41da040ef9a1d8466839|
8ac46a315e1ef48cfbe30e9d15242f8f73b322e8ede54c30d93f6859708d48f7|
2ac466861ca121d4c5e17970f4939cc3df3755a7fd90a6d11542b7432c03e215|docker.io/jboss/wildfly:latest
```

**Comment by bparees** [comment]
i think i like a space better than a | for the separator since awk can handle it by default that way rather than specifying a split character.

if you want the | in there, i'm ok with it, just put spaces on either side :)

**Comment by goldmann** [comment]
`-F\|` ?:) Space is not a good idea, because if you do `-ctm` then you'll not be able to differentiate between tag and command.

**Comment by bparees** [comment]
like I said, i wanted awk to work by default.  I always have to look up the -F syntax :)

i hadn't played with -c.  so ok, i concede :)
