### ISSUE TITLE
squashing layers removes required `docker_version` key

### ISSUE THREAD

**Issue by twaugh** [goldmann/docker-scripts#28]
After squashing layers, the remaining metadata is missing the 'docker_version' key. This should be preserved from the keys in the squashed layers.

**Comment by goldmann** [comment]
Hey Tim, since I'm not sure about the report, three questions:

1. Where is this "key" added?
2. What adds this key?
3. At what time of the build it is added?

Thanks!

**Comment by twaugh** [comment]
It's in the `<id>/json` file as a top-level field name. `docker build` adds it to the layers it builds.

For example, from `docker save busybox`:

```
$ json_reformat < 8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/json
{
    "id": "8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55",
[...]
    "docker_version": "1.6.0",
[...]
}
```

**Comment by twaugh** [comment]
The code that uses it is [in dockpulp](https://github.com/release-engineering/dockpulp/blob/master/dockpulp/imgutils.py#L65). It's used to verify that sufficiently recent versions of docker were used to build all the layers in the image.

**Comment by goldmann** [comment]
Thanks, I'll investigate and update the issue.

**Comment by goldmann** [comment]
I can confirm this, I'll try to understand why it does this and work on a fix.

**Comment by goldmann** [comment]
This is now fixed, a new version `0.4.1` was released.

**Comment by jpopelka** [comment]
I confirm that 0.4.1 fixes the problem. @goldmann would it be possible to update Fedora/epel with this ? Thanks !

**Comment by goldmann** [comment]
Available in Rawhide, update pushed to F21 and F22, for EPEL7 I'm waiting for the initial package to be pushed to stable, then I'll submit an update.
