### ISSUE TITLE
Option --tmp-dir is ignored during squashing

### ISSUE THREAD

**Issue by php-coder** [goldmann/docker-scripts#45]
As I can see [squash parser has --tmp-dir option](https://github.com/goldmann/docker-scripts/blob/8e1138b0b945e7782c0bf8b0462d62e856aa77c6/docker_scripts/cli.py#L58), it is parsed but [script doesn't pass this argument to Squash class](https://github.com/goldmann/docker-scripts/blob/8e1138b0b945e7782c0bf8b0462d62e856aa77c6/docker_scripts/cli.py#L29).

**Comment by goldmann** [comment]
I'll take a look at it, thanks for spotting this!

**Comment by php-coder** [comment]
P.S. I've found a workaround: because we are using `tempfile.mkdtemp()` we can change the root directory for temporary files by setting `TEMPDIR` environment variable. See [documentation](https://docs.python.org/2/library/tempfile.html#tempfile.tempdir) for details.
