### ISSUE TITLE
squash: purge working directory when user interrupts squashing with ^C

### ISSUE THREAD

**Issue by TomasTomecek** [goldmann/docker-scripts#5]

**Comment by goldmann** [comment]
I'm unsure if this is what we want to have - I'm using it for example for debugging. I start it with `-t tmp`, then hit `CTRL+C` if I want just part of the execution done. But I'm easy here.

We definitely should leave that directory in case of error for later investigation.

**Comment by TomasTomecek** [comment]
right! makes sense to me, so let's close this
